
# Config for model
model:
  type: mobilenet_v2
  package: torchvision.models
  kwargs:
    pretrain: true
    num_classes: 3

# Config for optimizer
optim:
  type: Adam
  package: torch.optim
  lr: 1e-4


# Config for data
data:
  train_data:
    data_folder:
    label_path:
    
    loader: #kwargs for dataloader
      batch_size: 16
  
  ptrain: 0.8 # Percent to split train when val_data=null


device: cuda
num_epochs: 10